version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tifull7.aprendizado
      MYSQL_DATABASE: taskdb
    ports:
      - "3308:33070"  # host-porta de acesso mysql:container pelo docker Você está expondo a porta do container MySQL 33070 para a porta 3308 no seu host. No container, o MySQL está rodando na porta 33070 (padrão 3306 foi alterado). Você mapeou 3308 na sua máquina para a porta 33070 dentro do container.
    command: --port=33070
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:33070/taskdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tifull7.aprendizado
      SPRING_RABBITMQ_HOST: rabbitmq

volumes:
  mysql-data:
